/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSyllabusIndexRouteImport } from './routes/_authenticated/syllabus/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReviewSchedulesIndexRouteImport } from './routes/_authenticated/review-schedules/index'
import { Route as AuthenticatedLecturerIndexRouteImport } from './routes/_authenticated/lecturer/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAcademicYearsIndexRouteImport } from './routes/_authenticated/academic-years/index'
import { Route as AuthenticatedSyllabusCreateRouteImport } from './routes/_authenticated/syllabus/create'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReviewSchedulesCreateRouteImport } from './routes/_authenticated/review-schedules/create'
import { Route as AuthenticatedPeerReviewIdRouteImport } from './routes/_authenticated/peer-review.$id'
import { Route as AuthenticatedLecturerNotificationsRouteImport } from './routes/_authenticated/lecturer/notifications'
import { Route as AuthenticatedLecturerNotificationPreferencesRouteImport } from './routes/_authenticated/lecturer/notification-preferences'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAcademicYearsAddRouteImport } from './routes/_authenticated/academic-years/add'
import { Route as AuthenticatedLecturerUpdateRequestsIndexRouteImport } from './routes/_authenticated/lecturer/update-requests/index'
import { Route as AuthenticatedLecturerSyllabiIndexRouteImport } from './routes/_authenticated/lecturer/syllabi/index'
import { Route as AuthenticatedLecturerReviewsIndexRouteImport } from './routes/_authenticated/lecturer/reviews/index'
import { Route as AuthenticatedLecturerMessagesIndexRouteImport } from './routes/_authenticated/lecturer/messages/index'
import { Route as AuthenticatedSyllabusViewIdRouteImport } from './routes/_authenticated/syllabus.view.$id'
import { Route as AuthenticatedSyllabusEditIdRouteImport } from './routes/_authenticated/syllabus.edit.$id'
import { Route as AuthenticatedSyllabusIdEditRouteImport } from './routes/_authenticated/syllabus/$id.edit'
import { Route as AuthenticatedReviewSchedulesViewIdRouteImport } from './routes/_authenticated/review-schedules/view.$id'
import { Route as AuthenticatedReviewSchedulesEditIdRouteImport } from './routes/_authenticated/review-schedules/edit.$id'
import { Route as AuthenticatedLecturerSyllabiCreateRouteImport } from './routes/_authenticated/lecturer/syllabi/create'
import { Route as AuthenticatedLecturerMessagesComposeRouteImport } from './routes/_authenticated/lecturer/messages/compose'
import { Route as AuthenticatedAcademicYearsEditIdRouteImport } from './routes/_authenticated/academic-years/edit.$id'
import { Route as AuthenticatedLecturerReviewsPeerReviewsIndexRouteImport } from './routes/_authenticated/lecturer/reviews/peer-reviews/index'
import { Route as AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRouteImport } from './routes/_authenticated/lecturer/update-requests/create.$syllabusId'
import { Route as AuthenticatedLecturerSyllabiIdSubmitRouteImport } from './routes/_authenticated/lecturer/syllabi/$id.submit'
import { Route as AuthenticatedLecturerSyllabiIdEditRouteImport } from './routes/_authenticated/lecturer/syllabi/$id.edit'
import { Route as AuthenticatedLecturerReviewsPeerReviewsIdRouteImport } from './routes/_authenticated/lecturer/reviews/peer-reviews/$id'
import { Route as AuthenticatedLecturerMessagesConversationUserIdRouteImport } from './routes/_authenticated/lecturer/messages/conversation.$userId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyllabusIndexRoute =
  AuthenticatedSyllabusIndexRouteImport.update({
    id: '/syllabus/',
    path: '/syllabus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReviewSchedulesIndexRoute =
  AuthenticatedReviewSchedulesIndexRouteImport.update({
    id: '/review-schedules/',
    path: '/review-schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerIndexRoute =
  AuthenticatedLecturerIndexRouteImport.update({
    id: '/lecturer/',
    path: '/lecturer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicYearsIndexRoute =
  AuthenticatedAcademicYearsIndexRouteImport.update({
    id: '/academic-years/',
    path: '/academic-years/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSyllabusCreateRoute =
  AuthenticatedSyllabusCreateRouteImport.update({
    id: '/syllabus/create',
    path: '/syllabus/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReviewSchedulesCreateRoute =
  AuthenticatedReviewSchedulesCreateRouteImport.update({
    id: '/review-schedules/create',
    path: '/review-schedules/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeerReviewIdRoute =
  AuthenticatedPeerReviewIdRouteImport.update({
    id: '/peer-review/$id',
    path: '/peer-review/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerNotificationsRoute =
  AuthenticatedLecturerNotificationsRouteImport.update({
    id: '/lecturer/notifications',
    path: '/lecturer/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerNotificationPreferencesRoute =
  AuthenticatedLecturerNotificationPreferencesRouteImport.update({
    id: '/lecturer/notification-preferences',
    path: '/lecturer/notification-preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsAddRoute =
  AuthenticatedAcademicYearsAddRouteImport.update({
    id: '/academic-years/add',
    path: '/academic-years/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerUpdateRequestsIndexRoute =
  AuthenticatedLecturerUpdateRequestsIndexRouteImport.update({
    id: '/lecturer/update-requests/',
    path: '/lecturer/update-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerSyllabiIndexRoute =
  AuthenticatedLecturerSyllabiIndexRouteImport.update({
    id: '/lecturer/syllabi/',
    path: '/lecturer/syllabi/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerReviewsIndexRoute =
  AuthenticatedLecturerReviewsIndexRouteImport.update({
    id: '/lecturer/reviews/',
    path: '/lecturer/reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerMessagesIndexRoute =
  AuthenticatedLecturerMessagesIndexRouteImport.update({
    id: '/lecturer/messages/',
    path: '/lecturer/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSyllabusViewIdRoute =
  AuthenticatedSyllabusViewIdRouteImport.update({
    id: '/syllabus/view/$id',
    path: '/syllabus/view/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSyllabusEditIdRoute =
  AuthenticatedSyllabusEditIdRouteImport.update({
    id: '/syllabus/edit/$id',
    path: '/syllabus/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSyllabusIdEditRoute =
  AuthenticatedSyllabusIdEditRouteImport.update({
    id: '/syllabus/$id/edit',
    path: '/syllabus/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewSchedulesViewIdRoute =
  AuthenticatedReviewSchedulesViewIdRouteImport.update({
    id: '/review-schedules/view/$id',
    path: '/review-schedules/view/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewSchedulesEditIdRoute =
  AuthenticatedReviewSchedulesEditIdRouteImport.update({
    id: '/review-schedules/edit/$id',
    path: '/review-schedules/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerSyllabiCreateRoute =
  AuthenticatedLecturerSyllabiCreateRouteImport.update({
    id: '/lecturer/syllabi/create',
    path: '/lecturer/syllabi/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerMessagesComposeRoute =
  AuthenticatedLecturerMessagesComposeRouteImport.update({
    id: '/lecturer/messages/compose',
    path: '/lecturer/messages/compose',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsEditIdRoute =
  AuthenticatedAcademicYearsEditIdRouteImport.update({
    id: '/academic-years/edit/$id',
    path: '/academic-years/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerReviewsPeerReviewsIndexRoute =
  AuthenticatedLecturerReviewsPeerReviewsIndexRouteImport.update({
    id: '/lecturer/reviews/peer-reviews/',
    path: '/lecturer/reviews/peer-reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute =
  AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRouteImport.update({
    id: '/lecturer/update-requests/create/$syllabusId',
    path: '/lecturer/update-requests/create/$syllabusId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerSyllabiIdSubmitRoute =
  AuthenticatedLecturerSyllabiIdSubmitRouteImport.update({
    id: '/lecturer/syllabi/$id/submit',
    path: '/lecturer/syllabi/$id/submit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerSyllabiIdEditRoute =
  AuthenticatedLecturerSyllabiIdEditRouteImport.update({
    id: '/lecturer/syllabi/$id/edit',
    path: '/lecturer/syllabi/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerReviewsPeerReviewsIdRoute =
  AuthenticatedLecturerReviewsPeerReviewsIdRouteImport.update({
    id: '/lecturer/reviews/peer-reviews/$id',
    path: '/lecturer/reviews/peer-reviews/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLecturerMessagesConversationUserIdRoute =
  AuthenticatedLecturerMessagesConversationUserIdRouteImport.update({
    id: '/lecturer/messages/conversation/$userId',
    path: '/lecturer/messages/conversation/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/academic-years/add': typeof AuthenticatedAcademicYearsAddRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/lecturer/notification-preferences': typeof AuthenticatedLecturerNotificationPreferencesRoute
  '/lecturer/notifications': typeof AuthenticatedLecturerNotificationsRoute
  '/peer-review/$id': typeof AuthenticatedPeerReviewIdRoute
  '/review-schedules/create': typeof AuthenticatedReviewSchedulesCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/syllabus/create': typeof AuthenticatedSyllabusCreateRoute
  '/academic-years': typeof AuthenticatedAcademicYearsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/lecturer': typeof AuthenticatedLecturerIndexRoute
  '/review-schedules': typeof AuthenticatedReviewSchedulesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/syllabus': typeof AuthenticatedSyllabusIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/academic-years/edit/$id': typeof AuthenticatedAcademicYearsEditIdRoute
  '/lecturer/messages/compose': typeof AuthenticatedLecturerMessagesComposeRoute
  '/lecturer/syllabi/create': typeof AuthenticatedLecturerSyllabiCreateRoute
  '/review-schedules/edit/$id': typeof AuthenticatedReviewSchedulesEditIdRoute
  '/review-schedules/view/$id': typeof AuthenticatedReviewSchedulesViewIdRoute
  '/syllabus/$id/edit': typeof AuthenticatedSyllabusIdEditRoute
  '/syllabus/edit/$id': typeof AuthenticatedSyllabusEditIdRoute
  '/syllabus/view/$id': typeof AuthenticatedSyllabusViewIdRoute
  '/lecturer/messages': typeof AuthenticatedLecturerMessagesIndexRoute
  '/lecturer/reviews': typeof AuthenticatedLecturerReviewsIndexRoute
  '/lecturer/syllabi': typeof AuthenticatedLecturerSyllabiIndexRoute
  '/lecturer/update-requests': typeof AuthenticatedLecturerUpdateRequestsIndexRoute
  '/lecturer/messages/conversation/$userId': typeof AuthenticatedLecturerMessagesConversationUserIdRoute
  '/lecturer/reviews/peer-reviews/$id': typeof AuthenticatedLecturerReviewsPeerReviewsIdRoute
  '/lecturer/syllabi/$id/edit': typeof AuthenticatedLecturerSyllabiIdEditRoute
  '/lecturer/syllabi/$id/submit': typeof AuthenticatedLecturerSyllabiIdSubmitRoute
  '/lecturer/update-requests/create/$syllabusId': typeof AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute
  '/lecturer/reviews/peer-reviews': typeof AuthenticatedLecturerReviewsPeerReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/academic-years/add': typeof AuthenticatedAcademicYearsAddRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/lecturer/notification-preferences': typeof AuthenticatedLecturerNotificationPreferencesRoute
  '/lecturer/notifications': typeof AuthenticatedLecturerNotificationsRoute
  '/peer-review/$id': typeof AuthenticatedPeerReviewIdRoute
  '/review-schedules/create': typeof AuthenticatedReviewSchedulesCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/syllabus/create': typeof AuthenticatedSyllabusCreateRoute
  '/academic-years': typeof AuthenticatedAcademicYearsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/lecturer': typeof AuthenticatedLecturerIndexRoute
  '/review-schedules': typeof AuthenticatedReviewSchedulesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/syllabus': typeof AuthenticatedSyllabusIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/academic-years/edit/$id': typeof AuthenticatedAcademicYearsEditIdRoute
  '/lecturer/messages/compose': typeof AuthenticatedLecturerMessagesComposeRoute
  '/lecturer/syllabi/create': typeof AuthenticatedLecturerSyllabiCreateRoute
  '/review-schedules/edit/$id': typeof AuthenticatedReviewSchedulesEditIdRoute
  '/review-schedules/view/$id': typeof AuthenticatedReviewSchedulesViewIdRoute
  '/syllabus/$id/edit': typeof AuthenticatedSyllabusIdEditRoute
  '/syllabus/edit/$id': typeof AuthenticatedSyllabusEditIdRoute
  '/syllabus/view/$id': typeof AuthenticatedSyllabusViewIdRoute
  '/lecturer/messages': typeof AuthenticatedLecturerMessagesIndexRoute
  '/lecturer/reviews': typeof AuthenticatedLecturerReviewsIndexRoute
  '/lecturer/syllabi': typeof AuthenticatedLecturerSyllabiIndexRoute
  '/lecturer/update-requests': typeof AuthenticatedLecturerUpdateRequestsIndexRoute
  '/lecturer/messages/conversation/$userId': typeof AuthenticatedLecturerMessagesConversationUserIdRoute
  '/lecturer/reviews/peer-reviews/$id': typeof AuthenticatedLecturerReviewsPeerReviewsIdRoute
  '/lecturer/syllabi/$id/edit': typeof AuthenticatedLecturerSyllabiIdEditRoute
  '/lecturer/syllabi/$id/submit': typeof AuthenticatedLecturerSyllabiIdSubmitRoute
  '/lecturer/update-requests/create/$syllabusId': typeof AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute
  '/lecturer/reviews/peer-reviews': typeof AuthenticatedLecturerReviewsPeerReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/academic-years/add': typeof AuthenticatedAcademicYearsAddRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/lecturer/notification-preferences': typeof AuthenticatedLecturerNotificationPreferencesRoute
  '/_authenticated/lecturer/notifications': typeof AuthenticatedLecturerNotificationsRoute
  '/_authenticated/peer-review/$id': typeof AuthenticatedPeerReviewIdRoute
  '/_authenticated/review-schedules/create': typeof AuthenticatedReviewSchedulesCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/syllabus/create': typeof AuthenticatedSyllabusCreateRoute
  '/_authenticated/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/lecturer/': typeof AuthenticatedLecturerIndexRoute
  '/_authenticated/review-schedules/': typeof AuthenticatedReviewSchedulesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/syllabus/': typeof AuthenticatedSyllabusIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/academic-years/edit/$id': typeof AuthenticatedAcademicYearsEditIdRoute
  '/_authenticated/lecturer/messages/compose': typeof AuthenticatedLecturerMessagesComposeRoute
  '/_authenticated/lecturer/syllabi/create': typeof AuthenticatedLecturerSyllabiCreateRoute
  '/_authenticated/review-schedules/edit/$id': typeof AuthenticatedReviewSchedulesEditIdRoute
  '/_authenticated/review-schedules/view/$id': typeof AuthenticatedReviewSchedulesViewIdRoute
  '/_authenticated/syllabus/$id/edit': typeof AuthenticatedSyllabusIdEditRoute
  '/_authenticated/syllabus/edit/$id': typeof AuthenticatedSyllabusEditIdRoute
  '/_authenticated/syllabus/view/$id': typeof AuthenticatedSyllabusViewIdRoute
  '/_authenticated/lecturer/messages/': typeof AuthenticatedLecturerMessagesIndexRoute
  '/_authenticated/lecturer/reviews/': typeof AuthenticatedLecturerReviewsIndexRoute
  '/_authenticated/lecturer/syllabi/': typeof AuthenticatedLecturerSyllabiIndexRoute
  '/_authenticated/lecturer/update-requests/': typeof AuthenticatedLecturerUpdateRequestsIndexRoute
  '/_authenticated/lecturer/messages/conversation/$userId': typeof AuthenticatedLecturerMessagesConversationUserIdRoute
  '/_authenticated/lecturer/reviews/peer-reviews/$id': typeof AuthenticatedLecturerReviewsPeerReviewsIdRoute
  '/_authenticated/lecturer/syllabi/$id/edit': typeof AuthenticatedLecturerSyllabiIdEditRoute
  '/_authenticated/lecturer/syllabi/$id/submit': typeof AuthenticatedLecturerSyllabiIdSubmitRoute
  '/_authenticated/lecturer/update-requests/create/$syllabusId': typeof AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute
  '/_authenticated/lecturer/reviews/peer-reviews/': typeof AuthenticatedLecturerReviewsPeerReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/academic-years/add'
    | '/errors/$error'
    | '/lecturer/notification-preferences'
    | '/lecturer/notifications'
    | '/peer-review/$id'
    | '/review-schedules/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/syllabus/create'
    | '/academic-years'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/lecturer'
    | '/review-schedules'
    | '/settings/'
    | '/syllabus'
    | '/tasks'
    | '/users'
    | '/academic-years/edit/$id'
    | '/lecturer/messages/compose'
    | '/lecturer/syllabi/create'
    | '/review-schedules/edit/$id'
    | '/review-schedules/view/$id'
    | '/syllabus/$id/edit'
    | '/syllabus/edit/$id'
    | '/syllabus/view/$id'
    | '/lecturer/messages'
    | '/lecturer/reviews'
    | '/lecturer/syllabi'
    | '/lecturer/update-requests'
    | '/lecturer/messages/conversation/$userId'
    | '/lecturer/reviews/peer-reviews/$id'
    | '/lecturer/syllabi/$id/edit'
    | '/lecturer/syllabi/$id/submit'
    | '/lecturer/update-requests/create/$syllabusId'
    | '/lecturer/reviews/peer-reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/academic-years/add'
    | '/errors/$error'
    | '/lecturer/notification-preferences'
    | '/lecturer/notifications'
    | '/peer-review/$id'
    | '/review-schedules/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/syllabus/create'
    | '/academic-years'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/lecturer'
    | '/review-schedules'
    | '/settings'
    | '/syllabus'
    | '/tasks'
    | '/users'
    | '/academic-years/edit/$id'
    | '/lecturer/messages/compose'
    | '/lecturer/syllabi/create'
    | '/review-schedules/edit/$id'
    | '/review-schedules/view/$id'
    | '/syllabus/$id/edit'
    | '/syllabus/edit/$id'
    | '/syllabus/view/$id'
    | '/lecturer/messages'
    | '/lecturer/reviews'
    | '/lecturer/syllabi'
    | '/lecturer/update-requests'
    | '/lecturer/messages/conversation/$userId'
    | '/lecturer/reviews/peer-reviews/$id'
    | '/lecturer/syllabi/$id/edit'
    | '/lecturer/syllabi/$id/submit'
    | '/lecturer/update-requests/create/$syllabusId'
    | '/lecturer/reviews/peer-reviews'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/academic-years/add'
    | '/_authenticated/errors/$error'
    | '/_authenticated/lecturer/notification-preferences'
    | '/_authenticated/lecturer/notifications'
    | '/_authenticated/peer-review/$id'
    | '/_authenticated/review-schedules/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/syllabus/create'
    | '/_authenticated/academic-years/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/lecturer/'
    | '/_authenticated/review-schedules/'
    | '/_authenticated/settings/'
    | '/_authenticated/syllabus/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/academic-years/edit/$id'
    | '/_authenticated/lecturer/messages/compose'
    | '/_authenticated/lecturer/syllabi/create'
    | '/_authenticated/review-schedules/edit/$id'
    | '/_authenticated/review-schedules/view/$id'
    | '/_authenticated/syllabus/$id/edit'
    | '/_authenticated/syllabus/edit/$id'
    | '/_authenticated/syllabus/view/$id'
    | '/_authenticated/lecturer/messages/'
    | '/_authenticated/lecturer/reviews/'
    | '/_authenticated/lecturer/syllabi/'
    | '/_authenticated/lecturer/update-requests/'
    | '/_authenticated/lecturer/messages/conversation/$userId'
    | '/_authenticated/lecturer/reviews/peer-reviews/$id'
    | '/_authenticated/lecturer/syllabi/$id/edit'
    | '/_authenticated/lecturer/syllabi/$id/submit'
    | '/_authenticated/lecturer/update-requests/create/$syllabusId'
    | '/_authenticated/lecturer/reviews/peer-reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabus/': {
      id: '/_authenticated/syllabus/'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof AuthenticatedSyllabusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/review-schedules/': {
      id: '/_authenticated/review-schedules/'
      path: '/review-schedules'
      fullPath: '/review-schedules'
      preLoaderRoute: typeof AuthenticatedReviewSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/': {
      id: '/_authenticated/lecturer/'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof AuthenticatedLecturerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/': {
      id: '/_authenticated/academic-years/'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabus/create': {
      id: '/_authenticated/syllabus/create'
      path: '/syllabus/create'
      fullPath: '/syllabus/create'
      preLoaderRoute: typeof AuthenticatedSyllabusCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/review-schedules/create': {
      id: '/_authenticated/review-schedules/create'
      path: '/review-schedules/create'
      fullPath: '/review-schedules/create'
      preLoaderRoute: typeof AuthenticatedReviewSchedulesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/peer-review/$id': {
      id: '/_authenticated/peer-review/$id'
      path: '/peer-review/$id'
      fullPath: '/peer-review/$id'
      preLoaderRoute: typeof AuthenticatedPeerReviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/notifications': {
      id: '/_authenticated/lecturer/notifications'
      path: '/lecturer/notifications'
      fullPath: '/lecturer/notifications'
      preLoaderRoute: typeof AuthenticatedLecturerNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/notification-preferences': {
      id: '/_authenticated/lecturer/notification-preferences'
      path: '/lecturer/notification-preferences'
      fullPath: '/lecturer/notification-preferences'
      preLoaderRoute: typeof AuthenticatedLecturerNotificationPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/add': {
      id: '/_authenticated/academic-years/add'
      path: '/academic-years/add'
      fullPath: '/academic-years/add'
      preLoaderRoute: typeof AuthenticatedAcademicYearsAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/update-requests/': {
      id: '/_authenticated/lecturer/update-requests/'
      path: '/lecturer/update-requests'
      fullPath: '/lecturer/update-requests'
      preLoaderRoute: typeof AuthenticatedLecturerUpdateRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/syllabi/': {
      id: '/_authenticated/lecturer/syllabi/'
      path: '/lecturer/syllabi'
      fullPath: '/lecturer/syllabi'
      preLoaderRoute: typeof AuthenticatedLecturerSyllabiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/reviews/': {
      id: '/_authenticated/lecturer/reviews/'
      path: '/lecturer/reviews'
      fullPath: '/lecturer/reviews'
      preLoaderRoute: typeof AuthenticatedLecturerReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/messages/': {
      id: '/_authenticated/lecturer/messages/'
      path: '/lecturer/messages'
      fullPath: '/lecturer/messages'
      preLoaderRoute: typeof AuthenticatedLecturerMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabus/view/$id': {
      id: '/_authenticated/syllabus/view/$id'
      path: '/syllabus/view/$id'
      fullPath: '/syllabus/view/$id'
      preLoaderRoute: typeof AuthenticatedSyllabusViewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabus/edit/$id': {
      id: '/_authenticated/syllabus/edit/$id'
      path: '/syllabus/edit/$id'
      fullPath: '/syllabus/edit/$id'
      preLoaderRoute: typeof AuthenticatedSyllabusEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabus/$id/edit': {
      id: '/_authenticated/syllabus/$id/edit'
      path: '/syllabus/$id/edit'
      fullPath: '/syllabus/$id/edit'
      preLoaderRoute: typeof AuthenticatedSyllabusIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review-schedules/view/$id': {
      id: '/_authenticated/review-schedules/view/$id'
      path: '/review-schedules/view/$id'
      fullPath: '/review-schedules/view/$id'
      preLoaderRoute: typeof AuthenticatedReviewSchedulesViewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review-schedules/edit/$id': {
      id: '/_authenticated/review-schedules/edit/$id'
      path: '/review-schedules/edit/$id'
      fullPath: '/review-schedules/edit/$id'
      preLoaderRoute: typeof AuthenticatedReviewSchedulesEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/syllabi/create': {
      id: '/_authenticated/lecturer/syllabi/create'
      path: '/lecturer/syllabi/create'
      fullPath: '/lecturer/syllabi/create'
      preLoaderRoute: typeof AuthenticatedLecturerSyllabiCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/messages/compose': {
      id: '/_authenticated/lecturer/messages/compose'
      path: '/lecturer/messages/compose'
      fullPath: '/lecturer/messages/compose'
      preLoaderRoute: typeof AuthenticatedLecturerMessagesComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/edit/$id': {
      id: '/_authenticated/academic-years/edit/$id'
      path: '/academic-years/edit/$id'
      fullPath: '/academic-years/edit/$id'
      preLoaderRoute: typeof AuthenticatedAcademicYearsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/reviews/peer-reviews/': {
      id: '/_authenticated/lecturer/reviews/peer-reviews/'
      path: '/lecturer/reviews/peer-reviews'
      fullPath: '/lecturer/reviews/peer-reviews'
      preLoaderRoute: typeof AuthenticatedLecturerReviewsPeerReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/update-requests/create/$syllabusId': {
      id: '/_authenticated/lecturer/update-requests/create/$syllabusId'
      path: '/lecturer/update-requests/create/$syllabusId'
      fullPath: '/lecturer/update-requests/create/$syllabusId'
      preLoaderRoute: typeof AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/syllabi/$id/submit': {
      id: '/_authenticated/lecturer/syllabi/$id/submit'
      path: '/lecturer/syllabi/$id/submit'
      fullPath: '/lecturer/syllabi/$id/submit'
      preLoaderRoute: typeof AuthenticatedLecturerSyllabiIdSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/syllabi/$id/edit': {
      id: '/_authenticated/lecturer/syllabi/$id/edit'
      path: '/lecturer/syllabi/$id/edit'
      fullPath: '/lecturer/syllabi/$id/edit'
      preLoaderRoute: typeof AuthenticatedLecturerSyllabiIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/reviews/peer-reviews/$id': {
      id: '/_authenticated/lecturer/reviews/peer-reviews/$id'
      path: '/lecturer/reviews/peer-reviews/$id'
      fullPath: '/lecturer/reviews/peer-reviews/$id'
      preLoaderRoute: typeof AuthenticatedLecturerReviewsPeerReviewsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecturer/messages/conversation/$userId': {
      id: '/_authenticated/lecturer/messages/conversation/$userId'
      path: '/lecturer/messages/conversation/$userId'
      fullPath: '/lecturer/messages/conversation/$userId'
      preLoaderRoute: typeof AuthenticatedLecturerMessagesConversationUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAcademicYearsAddRoute: typeof AuthenticatedAcademicYearsAddRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedLecturerNotificationPreferencesRoute: typeof AuthenticatedLecturerNotificationPreferencesRoute
  AuthenticatedLecturerNotificationsRoute: typeof AuthenticatedLecturerNotificationsRoute
  AuthenticatedPeerReviewIdRoute: typeof AuthenticatedPeerReviewIdRoute
  AuthenticatedReviewSchedulesCreateRoute: typeof AuthenticatedReviewSchedulesCreateRoute
  AuthenticatedSyllabusCreateRoute: typeof AuthenticatedSyllabusCreateRoute
  AuthenticatedAcademicYearsIndexRoute: typeof AuthenticatedAcademicYearsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLecturerIndexRoute: typeof AuthenticatedLecturerIndexRoute
  AuthenticatedReviewSchedulesIndexRoute: typeof AuthenticatedReviewSchedulesIndexRoute
  AuthenticatedSyllabusIndexRoute: typeof AuthenticatedSyllabusIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAcademicYearsEditIdRoute: typeof AuthenticatedAcademicYearsEditIdRoute
  AuthenticatedLecturerMessagesComposeRoute: typeof AuthenticatedLecturerMessagesComposeRoute
  AuthenticatedLecturerSyllabiCreateRoute: typeof AuthenticatedLecturerSyllabiCreateRoute
  AuthenticatedReviewSchedulesEditIdRoute: typeof AuthenticatedReviewSchedulesEditIdRoute
  AuthenticatedReviewSchedulesViewIdRoute: typeof AuthenticatedReviewSchedulesViewIdRoute
  AuthenticatedSyllabusIdEditRoute: typeof AuthenticatedSyllabusIdEditRoute
  AuthenticatedSyllabusEditIdRoute: typeof AuthenticatedSyllabusEditIdRoute
  AuthenticatedSyllabusViewIdRoute: typeof AuthenticatedSyllabusViewIdRoute
  AuthenticatedLecturerMessagesIndexRoute: typeof AuthenticatedLecturerMessagesIndexRoute
  AuthenticatedLecturerReviewsIndexRoute: typeof AuthenticatedLecturerReviewsIndexRoute
  AuthenticatedLecturerSyllabiIndexRoute: typeof AuthenticatedLecturerSyllabiIndexRoute
  AuthenticatedLecturerUpdateRequestsIndexRoute: typeof AuthenticatedLecturerUpdateRequestsIndexRoute
  AuthenticatedLecturerMessagesConversationUserIdRoute: typeof AuthenticatedLecturerMessagesConversationUserIdRoute
  AuthenticatedLecturerReviewsPeerReviewsIdRoute: typeof AuthenticatedLecturerReviewsPeerReviewsIdRoute
  AuthenticatedLecturerSyllabiIdEditRoute: typeof AuthenticatedLecturerSyllabiIdEditRoute
  AuthenticatedLecturerSyllabiIdSubmitRoute: typeof AuthenticatedLecturerSyllabiIdSubmitRoute
  AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute: typeof AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute
  AuthenticatedLecturerReviewsPeerReviewsIndexRoute: typeof AuthenticatedLecturerReviewsPeerReviewsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAcademicYearsAddRoute: AuthenticatedAcademicYearsAddRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedLecturerNotificationPreferencesRoute:
    AuthenticatedLecturerNotificationPreferencesRoute,
  AuthenticatedLecturerNotificationsRoute:
    AuthenticatedLecturerNotificationsRoute,
  AuthenticatedPeerReviewIdRoute: AuthenticatedPeerReviewIdRoute,
  AuthenticatedReviewSchedulesCreateRoute:
    AuthenticatedReviewSchedulesCreateRoute,
  AuthenticatedSyllabusCreateRoute: AuthenticatedSyllabusCreateRoute,
  AuthenticatedAcademicYearsIndexRoute: AuthenticatedAcademicYearsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLecturerIndexRoute: AuthenticatedLecturerIndexRoute,
  AuthenticatedReviewSchedulesIndexRoute:
    AuthenticatedReviewSchedulesIndexRoute,
  AuthenticatedSyllabusIndexRoute: AuthenticatedSyllabusIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAcademicYearsEditIdRoute: AuthenticatedAcademicYearsEditIdRoute,
  AuthenticatedLecturerMessagesComposeRoute:
    AuthenticatedLecturerMessagesComposeRoute,
  AuthenticatedLecturerSyllabiCreateRoute:
    AuthenticatedLecturerSyllabiCreateRoute,
  AuthenticatedReviewSchedulesEditIdRoute:
    AuthenticatedReviewSchedulesEditIdRoute,
  AuthenticatedReviewSchedulesViewIdRoute:
    AuthenticatedReviewSchedulesViewIdRoute,
  AuthenticatedSyllabusIdEditRoute: AuthenticatedSyllabusIdEditRoute,
  AuthenticatedSyllabusEditIdRoute: AuthenticatedSyllabusEditIdRoute,
  AuthenticatedSyllabusViewIdRoute: AuthenticatedSyllabusViewIdRoute,
  AuthenticatedLecturerMessagesIndexRoute:
    AuthenticatedLecturerMessagesIndexRoute,
  AuthenticatedLecturerReviewsIndexRoute:
    AuthenticatedLecturerReviewsIndexRoute,
  AuthenticatedLecturerSyllabiIndexRoute:
    AuthenticatedLecturerSyllabiIndexRoute,
  AuthenticatedLecturerUpdateRequestsIndexRoute:
    AuthenticatedLecturerUpdateRequestsIndexRoute,
  AuthenticatedLecturerMessagesConversationUserIdRoute:
    AuthenticatedLecturerMessagesConversationUserIdRoute,
  AuthenticatedLecturerReviewsPeerReviewsIdRoute:
    AuthenticatedLecturerReviewsPeerReviewsIdRoute,
  AuthenticatedLecturerSyllabiIdEditRoute:
    AuthenticatedLecturerSyllabiIdEditRoute,
  AuthenticatedLecturerSyllabiIdSubmitRoute:
    AuthenticatedLecturerSyllabiIdSubmitRoute,
  AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute:
    AuthenticatedLecturerUpdateRequestsCreateSyllabusIdRoute,
  AuthenticatedLecturerReviewsPeerReviewsIndexRoute:
    AuthenticatedLecturerReviewsPeerReviewsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
